---
openshift_deployment_type: origin
openshift_release: 1.5.1
#openshift_deployment_type: openshift-enterprise
#openshift_release: v3.5
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

openshift_master_cluster_method: native
openshift_master_cluster_hostname: "{{ groups.lb.0|default(groups.masters.0) }}"
openshift_master_cluster_public_hostname: "{{ groups.lb.0|default(groups.masters.0) }}"

#openshift_cluster_node_labels:
#  app:
#    region: primary
#  infra:
#    region: infra

osm_default_node_selector: 'region=primary'

# htpasswd auth
openshift_master_identity_providers:
  - name: htpasswd_auth
    login: true
    challenge: true
    kind: HTPasswdPasswordIdentityProvider
    filename: /etc/origin/master/htpasswd
# Define htpasswd users, like:
# export MYSECRET=$(htpasswd -nbm user1 Cvnmvnslslkjdgh123t6|awk -F ':' '{print $2}')
openshift_master_htpasswd_users: 
  user1: "{{ lookup('env', 'MYSECRET') }}"

# NOTE(shadower): the hostname check seems to always fail because the
# host's floating IP address doesn't match the address received from
# inside the host.
openshift_override_hostname_check: true

# For POCs or demo environments that are using smaller instances than
# the official recommended values for RAM and DISK, uncomment the line below.
#openshift_disable_check: disk_availability,memory_availability
openshift_disable_check: disk_availability,memory_availability,package_availability,docker_image_availability,docker_storage,package_version

# NOTE(shadower): Always switch to root on the OSEv3 nodes.
# openshift-ansible requires an explicit `become`.
ansible_become: true
