---
openshift_deployment_type: origin
openshift_release: 1.5.1
#openshift_deployment_type: openshift-enterprise
#openshift_release: v3.5
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

#openshift_cluster_node_labels:
#  app:
#    region: primary
#  infra:
#    region: infra

osm_default_node_selector: 'region=primary'

# htpasswd auth
openshift_master_identity_providers:
  - name: htpasswd_auth
    login: true
    challenge: true
    kind: HTPasswdPasswordIdentityProvider
    filename: /etc/origin/master/htpasswd
# Define htpasswd users, like:
# export MYSECRET=$(htpasswd -nbm user1 Cvnmvnslslkjdgh123t6|awk -F ':' '{print $2}')
openshift_master_htpasswd_users: 
  user1: "{{ lookup('env', 'MYSECRET') }}"

openshift_override_hostname_check: true
openshift_disable_check: disk_availability,memory_availability,package_availability,docker_image_availability,docker_storage,package_version
