---
openshift_deployment_type: openshift-enterprise
openshift_release: v3.5
openshift_master_default_subdomain: apps.{{openstack_dns_domain}}

# NOTE(shadower): do not remove this line, otherwise the default node labels
# won't be set up.
openshift_node_labels: "{{ openstack.metadata.node_labels }}"

osm_default_node_selector: 'region=primary'

# htpasswd auth
openshift_master_identity_providers:
  - {'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}
# Defining htpasswd users
openshift_master_htpasswd_users: {'user1': '$2y$05$OUDHirUnCTsewM13dNEwZ.Di5/oBD/3iEt8pEfL5P4KbcT8uxtWL'}
