---
- hosts: localhost
  gather_facts: True
  become: False
  roles:
    - role: galaxy/openshift-ansible-contrib/roles/static_inventory
      when: openstack_inventory|default('static') == 'static'
      inventory_path: "{{ openstack_inventory_path|default(lookup('env','PWD') + '/inventory') }}"
      private_ssh_key: "{{ openstack_private_ssh_key|default('') }}"
      ssh_config_path: "{{ openstack_ssh_config_path|default('/tmp/ssh.config.openshift.ansible') }}"
      ssh_user: "{{ ansible_user }}"
      stack_name: "{{ openshift_openstack_clusterid }}.{{ openshift_openstack_public_dns_domain }}"
      use_bastion: "{{ openshift_openstack_use_bastion|default(false) }}"
      ui_ssh_tunnel: "{{ openshift_openstack_ui_ssh_tunnel|default(false) }}"
      openstack_private_network: "{{ openshift_openstack_private_network_name|default('private') }}"

- name: Refresh Server inventory or exit to apply SSH config
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  tasks:
    - name: Exit to apply SSH config for a bastion
      meta: end_play
      when: openstack_use_bastion|default(False)|bool
    - name: Refresh Server inventory
      meta: refresh_inventory
